package migration

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type FileRecord struct {
	Path     string `json:"path"`
	Category string `json:"category"`
	Language string `json:"language"`
}

type Summary struct {
	NonGoFiles             int `json:"non_go_files"`
	LegacyRuntimeFiles     int `json:"legacy_runtime_files"`
	LegacyTestFiles        int `json:"legacy_test_files"`
	PythonScriptFiles      int `json:"python_script_files"`
	ShellScriptFiles       int `json:"shell_script_files"`
	PythonToolchainFiles   int `json:"python_toolchain_files"`
	ValidationHarnessFiles int `json:"validation_harness_files"`
	FirstBatchSliceCount   int `json:"first_batch_slice_count"`
	ParallelSliceCount     int `json:"parallel_slice_count"`
}

type Slice struct {
	Identifier   string   `json:"identifier"`
	Title        string   `json:"title"`
	Phase        string   `json:"phase"`
	Priority     string   `json:"priority"`
	Status       string   `json:"status"`
	FirstBatch   bool     `json:"first_batch"`
	Scope        string   `json:"scope"`
	TargetPaths  []string `json:"target_paths"`
	Dependencies []string `json:"dependencies,omitempty"`
	Validation   []string `json:"validation"`
}

type Strategy struct {
	BranchPrefix        string   `json:"branch_prefix"`
	PRTitleTemplate     string   `json:"pr_title_template"`
	ExecutionPolicy     []string `json:"execution_policy"`
	ValidationPolicy    []string `json:"validation_policy"`
	CutoverPolicy       []string `json:"cutover_policy"`
	FirstBatchExecution []string `json:"first_batch_execution"`
}

type Report struct {
	Summary   Summary      `json:"summary"`
	Inventory []FileRecord `json:"inventory"`
	Slices    []Slice      `json:"slices"`
	Strategy  Strategy     `json:"strategy"`
}

func BuildReport(repoRoot string) (Report, error) {
	inventory, err := scanInventory(repoRoot)
	if err != nil {
		return Report{}, err
	}
	slices := defaultSlices()
	report := Report{
		Inventory: inventory,
		Slices:    slices,
		Strategy:  defaultStrategy(),
	}
	report.Summary = buildSummary(inventory, slices)
	return report, nil
}

func MarshalReport(report Report) ([]byte, error) {
	return json.MarshalIndent(report, "", "  ")
}

func RenderMarkdown(report Report) string {
	var b strings.Builder
	b.WriteString("# BigClaw Go-Only Migration Plan\n\n")
	b.WriteString("This plan is generated by `bigclawctl go-migration plan` and is the repo-native control surface for retiring the remaining Python and non-Go implementation paths.\n\n")
	b.WriteString("## Acceptance\n\n")
	b.WriteString("- Maintain `main` as Go-first while retiring remaining Python and non-Go runtime, script, test, and toolchain surfaces in batches.\n")
	b.WriteString("- Keep the migration inventory explicit so every remaining non-Go path has an owner and a retirement lane.\n")
	b.WriteString(fmt.Sprintf("- Run at least %d parallel slices under Symphony without forcing one large cutover PR.\n\n", report.Summary.ParallelSliceCount))

	b.WriteString("## Inventory Summary\n\n")
	b.WriteString(fmt.Sprintf("- Remaining non-Go files tracked: `%d`\n", report.Summary.NonGoFiles))
	b.WriteString(fmt.Sprintf("- Legacy runtime Python files under `src/bigclaw/`: `%d`\n", report.Summary.LegacyRuntimeFiles))
	b.WriteString(fmt.Sprintf("- Legacy Python test files under `tests/`: `%d`\n", report.Summary.LegacyTestFiles))
	b.WriteString(fmt.Sprintf("- Python script files: `%d`\n", report.Summary.PythonScriptFiles))
	b.WriteString(fmt.Sprintf("- Shell script files: `%d`\n", report.Summary.ShellScriptFiles))
	b.WriteString(fmt.Sprintf("- Python toolchain files: `%d`\n", report.Summary.PythonToolchainFiles))
	b.WriteString(fmt.Sprintf("- Validation-harness Python/shell files under `bigclaw-go/scripts/`: `%d`\n\n", report.Summary.ValidationHarnessFiles))

	b.WriteString("Canonical machine-readable inventory: `docs/reports/go-only-migration-inventory.json`\n\n")

	b.WriteString("## Parallel Slice Plan\n\n")
	for _, slice := range report.Slices {
		firstBatch := "no"
		if slice.FirstBatch {
			firstBatch = "yes"
		}
		b.WriteString(fmt.Sprintf("### %s %s\n\n", slice.Identifier, slice.Title))
		b.WriteString(fmt.Sprintf("- Phase: `%s`\n", slice.Phase))
		b.WriteString(fmt.Sprintf("- Priority: `%s`\n", slice.Priority))
		b.WriteString(fmt.Sprintf("- First batch: `%s`\n", firstBatch))
		b.WriteString(fmt.Sprintf("- Scope: %s\n", slice.Scope))
		b.WriteString("- Target paths:\n")
		for _, path := range slice.TargetPaths {
			b.WriteString(fmt.Sprintf("  - `%s`\n", path))
		}
		if len(slice.Dependencies) > 0 {
			b.WriteString("- Dependencies:\n")
			for _, dependency := range slice.Dependencies {
				b.WriteString(fmt.Sprintf("  - `%s`\n", dependency))
			}
		}
		b.WriteString("- Validation:\n")
		for _, validation := range slice.Validation {
			b.WriteString(fmt.Sprintf("  - `%s`\n", validation))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Branch And PR Strategy\n\n")
	b.WriteString(fmt.Sprintf("- Branch naming: `%s<slice-id>`\n", report.Strategy.BranchPrefix))
	b.WriteString(fmt.Sprintf("- PR title template: `%s`\n", report.Strategy.PRTitleTemplate))
	for _, line := range report.Strategy.ExecutionPolicy {
		b.WriteString(fmt.Sprintf("- %s\n", line))
	}
	for _, line := range report.Strategy.ValidationPolicy {
		b.WriteString(fmt.Sprintf("- %s\n", line))
	}
	for _, line := range report.Strategy.CutoverPolicy {
		b.WriteString(fmt.Sprintf("- %s\n", line))
	}
	b.WriteString("\n## First Batch Execution\n\n")
	for _, line := range report.Strategy.FirstBatchExecution {
		b.WriteString(fmt.Sprintf("- %s\n", line))
	}
	return b.String()
}

func scanInventory(repoRoot string) ([]FileRecord, error) {
	records := []FileRecord{}
	err := filepath.WalkDir(repoRoot, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, err := filepath.Rel(repoRoot, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if rel == "." {
			return nil
		}
		if d.IsDir() {
			switch rel {
			case ".git", ".symphony":
				return filepath.SkipDir
			}
			return nil
		}
		record, ok := classifyFile(repoRoot, rel)
		if ok {
			records = append(records, record)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(records, func(i, j int) bool {
		if records[i].Category == records[j].Category {
			return records[i].Path < records[j].Path
		}
		return records[i].Category < records[j].Category
	})
	return records, nil
}

func classifyFile(repoRoot string, relativePath string) (FileRecord, bool) {
	lower := strings.ToLower(relativePath)
	extension := strings.ToLower(filepath.Ext(lower))
	switch {
	case lower == "setup.py" || lower == "pyproject.toml":
		return FileRecord{Path: relativePath, Category: "python-toolchain", Language: "python"}, true
	case strings.HasPrefix(lower, "src/bigclaw/") && extension == ".py":
		return FileRecord{Path: relativePath, Category: "legacy-runtime", Language: "python"}, true
	case strings.HasPrefix(lower, "tests/") && extension == ".py":
		return FileRecord{Path: relativePath, Category: "legacy-tests", Language: "python"}, true
	case strings.HasPrefix(lower, "scripts/") && extension == ".py":
		return FileRecord{Path: relativePath, Category: "repo-script", Language: "python"}, true
	case strings.HasPrefix(lower, "scripts/") && (extension == ".sh" || isScriptWithoutExtension(repoRoot, relativePath)):
		return FileRecord{Path: relativePath, Category: "repo-script", Language: "shell"}, true
	case strings.HasPrefix(lower, "bigclaw-go/scripts/") && extension == ".py":
		return FileRecord{Path: relativePath, Category: "validation-harness", Language: "python"}, true
	case strings.HasPrefix(lower, "bigclaw-go/scripts/") && (extension == ".sh" || isScriptWithoutExtension(repoRoot, relativePath)):
		return FileRecord{Path: relativePath, Category: "validation-harness", Language: "shell"}, true
	default:
		return FileRecord{}, false
	}
}

func isScriptWithoutExtension(repoRoot string, relativePath string) bool {
	if filepath.Ext(relativePath) != "" {
		return false
	}
	body, err := os.ReadFile(filepath.Join(repoRoot, relativePath))
	if err != nil {
		return false
	}
	return strings.HasPrefix(string(body), "#!")
}

func buildSummary(inventory []FileRecord, slices []Slice) Summary {
	summary := Summary{NonGoFiles: len(inventory), ParallelSliceCount: len(slices)}
	for _, record := range inventory {
		switch record.Category {
		case "legacy-runtime":
			summary.LegacyRuntimeFiles++
		case "legacy-tests":
			summary.LegacyTestFiles++
		case "repo-script":
			if record.Language == "python" {
				summary.PythonScriptFiles++
			}
			if record.Language == "shell" {
				summary.ShellScriptFiles++
			}
		case "python-toolchain":
			summary.PythonToolchainFiles++
		case "validation-harness":
			summary.ValidationHarnessFiles++
			if record.Language == "python" {
				summary.PythonScriptFiles++
			}
			if record.Language == "shell" {
				summary.ShellScriptFiles++
			}
		}
	}
	for _, slice := range slices {
		if slice.FirstBatch {
			summary.FirstBatchSliceCount++
		}
	}
	return summary
}

func defaultSlices() []Slice {
	return []Slice{
		{
			Identifier:  "BIG-VNEXT-GO-101",
			Title:       "Go migration inventory and tracker control plane",
			Phase:       "Phase 0 / Planning",
			Priority:    "P0",
			Status:      "done",
			FirstBatch:  true,
			Scope:       "Generate the canonical inventory, slice plan, and tracker seed so all later migration work is queued from Go-owned control surfaces.",
			TargetPaths: []string{"bigclaw-go/internal/migration", "bigclaw-go/cmd/bigclawctl", "docs/go-only-migration-plan.md", "docs/reports/go-only-migration-inventory.json", "local-issues.json"},
			Validation:  []string{"cd bigclaw-go && go test ./internal/migration ./cmd/bigclawctl", "cd bigclaw-go && go run ./cmd/bigclawctl go-migration plan --repo .. --json-out ../docs/reports/go-only-migration-inventory.json --md-out ../docs/go-only-migration-plan.md"},
		},
		{
			Identifier:   "BIG-VNEXT-GO-102",
			Title:        "Retire root Python runtime entrypoints",
			Phase:        "Phase 1 / Runtime",
			Priority:     "P0",
			Status:       "todo",
			FirstBatch:   true,
			Scope:        "Replace `src/bigclaw` runtime entrypoints and module-level operators with Go-owned equivalents or explicit frozen shims.",
			TargetPaths:  []string{"src/bigclaw", "bigclaw-go/internal", "bigclaw-go/cmd"},
			Dependencies: []string{"BIG-VNEXT-GO-101"},
			Validation:   []string{"cd bigclaw-go && go test ./...", "bash scripts/ops/bigclawctl legacy-python compile-check --json"},
		},
		{
			Identifier:   "BIG-VNEXT-GO-103",
			Title:        "Migrate root Python test suite to Go coverage",
			Phase:        "Phase 1 / Tests",
			Priority:     "P0",
			Status:       "todo",
			FirstBatch:   true,
			Scope:        "Move behavioral coverage from `tests/*.py` into Go package and regression tests so the root pytest harness can be retired.",
			TargetPaths:  []string{"tests", "bigclaw-go/internal", "bigclaw-go/cmd"},
			Dependencies: []string{"BIG-VNEXT-GO-101"},
			Validation:   []string{"cd bigclaw-go && go test ./...", "rg --files tests"},
		},
		{
			Identifier:   "BIG-VNEXT-GO-104",
			Title:        "Replace repo ops Python wrappers with Go commands",
			Phase:        "Phase 1 / Tooling",
			Priority:     "P0",
			Status:       "todo",
			FirstBatch:   true,
			Scope:        "Collapse root `scripts/ops` Python and shell wrappers into `bigclawctl` or dedicated Go binaries.",
			TargetPaths:  []string{"scripts/ops", "bigclaw-go/cmd/bigclawctl", "bigclaw-go/internal/bootstrap", "bigclaw-go/internal/githubsync", "bigclaw-go/internal/refill"},
			Dependencies: []string{"BIG-VNEXT-GO-101"},
			Validation:   []string{"cd bigclaw-go && go test ./cmd/bigclawctl ./internal/bootstrap ./internal/githubsync ./internal/refill/...", "rg --files scripts/ops"},
		},
		{
			Identifier:   "BIG-VNEXT-GO-105",
			Title:        "Convert Go-side validation harness scripts to Go",
			Phase:        "Phase 2 / Validation",
			Priority:     "P0",
			Status:       "todo",
			FirstBatch:   false,
			Scope:        "Replace Python and shell harnesses under `bigclaw-go/scripts` with Go test helpers or Go commands so validation remains Go-only.",
			TargetPaths:  []string{"bigclaw-go/scripts/e2e", "bigclaw-go/scripts/benchmark", "bigclaw-go/scripts/migration", "bigclaw-go/internal/regression"},
			Dependencies: []string{"BIG-VNEXT-GO-101", "BIG-VNEXT-GO-103"},
			Validation:   []string{"cd bigclaw-go && go test ./internal/regression ./internal/events ./internal/api", "rg --files bigclaw-go/scripts"},
		},
		{
			Identifier:   "BIG-VNEXT-GO-106",
			Title:        "Remove Python packaging and bootstrap assumptions",
			Phase:        "Phase 2 / Toolchain",
			Priority:     "P1",
			Status:       "todo",
			FirstBatch:   false,
			Scope:        "Delete Python packaging metadata once runtime, tests, and operators no longer depend on it.",
			TargetPaths:  []string{"setup.py", "pyproject.toml", "README.md", "bigclaw-go/go.mod"},
			Dependencies: []string{"BIG-VNEXT-GO-102", "BIG-VNEXT-GO-103", "BIG-VNEXT-GO-104"},
			Validation:   []string{"cd bigclaw-go && go test ./...", "rg -n \"pytest|python3|PYTHONPATH|setup.py|pyproject.toml\" README.md docs scripts bigclaw-go"},
		},
		{
			Identifier:   "BIG-VNEXT-GO-107",
			Title:        "Migrate dev smoke and bootstrap helpers to Go",
			Phase:        "Phase 2 / Developer Experience",
			Priority:     "P1",
			Status:       "todo",
			FirstBatch:   false,
			Scope:        "Replace repo bootstrap and smoke helpers currently implemented as Python or shell scripts with Go-owned developer flows.",
			TargetPaths:  []string{"scripts/dev_bootstrap.sh", "scripts/dev_smoke.py", "scripts/create_issues.py", "bigclaw-go/cmd/bigclawctl"},
			Dependencies: []string{"BIG-VNEXT-GO-104"},
			Validation:   []string{"cd bigclaw-go && go test ./cmd/bigclawctl", "rg --files scripts | sort"},
		},
		{
			Identifier:   "BIG-VNEXT-GO-108",
			Title:        "Freeze or delete legacy Python source tree",
			Phase:        "Phase 3 / Retirement",
			Priority:     "P0",
			Status:       "todo",
			FirstBatch:   false,
			Scope:        "Once Go parity is proven, remove or hard-freeze the root Python source tree and leave only explicit compatibility stubs if absolutely required.",
			TargetPaths:  []string{"src/bigclaw", "README.md", "docs"},
			Dependencies: []string{"BIG-VNEXT-GO-102", "BIG-VNEXT-GO-103", "BIG-VNEXT-GO-104"},
			Validation:   []string{"bash scripts/ops/bigclawctl legacy-python compile-check --json", "rg --files src/bigclaw tests scripts | head"},
		},
		{
			Identifier:   "BIG-VNEXT-GO-109",
			Title:        "Cut docs and contributor flows to Go-only",
			Phase:        "Phase 3 / Docs",
			Priority:     "P1",
			Status:       "todo",
			FirstBatch:   false,
			Scope:        "Update README and operator docs so contributor guidance no longer points at Python or mixed-language workflows.",
			TargetPaths:  []string{"README.md", "docs", "workflow.md", "bigclaw-go/README.md"},
			Dependencies: []string{"BIG-VNEXT-GO-104", "BIG-VNEXT-GO-106"},
			Validation:   []string{"rg -n \"python|pytest|PYTHONPATH|setup.py\" README.md docs workflow.md bigclaw-go/README.md", "cd bigclaw-go && go test ./internal/regression"},
		},
		{
			Identifier:   "BIG-VNEXT-GO-110",
			Title:        "Run final Go-only cutover gate",
			Phase:        "Phase 4 / Cutover",
			Priority:     "P0",
			Status:       "todo",
			FirstBatch:   false,
			Scope:        "Execute the final repository-wide gate proving active development, validation, and operator workflows are Go-only.",
			TargetPaths:  []string{"bigclaw-go", "README.md", "docs", "scripts", "src/bigclaw", "tests"},
			Dependencies: []string{"BIG-VNEXT-GO-105", "BIG-VNEXT-GO-106", "BIG-VNEXT-GO-107", "BIG-VNEXT-GO-108", "BIG-VNEXT-GO-109"},
			Validation:   []string{"cd bigclaw-go && go test ./...", "rg --files -g'*.py' -g'*.sh' src tests scripts bigclaw-go/scripts", "git grep -n \"python3\\|pytest\\|PYTHONPATH\""},
		},
	}
}

func defaultStrategy() Strategy {
	return Strategy{
		BranchPrefix:    "symphony/",
		PRTitleTemplate: "BIG-VNEXT-GO-xxx: <slice title>",
		ExecutionPolicy: []string{
			"Keep slices branch-local and small enough to merge independently into `main`.",
			"Do not mix runtime migration, test migration, and toolchain retirement in one PR unless a later slice depends on the previous merge.",
			"Use the generated slice identifiers as the stable Symphony branch and tracker references.",
		},
		ValidationPolicy: []string{
			"Every slice must run targeted `go test` commands for the touched Go packages.",
			"Tracker closeout must record exact commands and pass/fail results, not generic statements.",
			"Cutover-facing slices must also rerun `go test ./...` from `bigclaw-go` before merge.",
		},
		CutoverPolicy: []string{
			"Do not delete Python or shell surfaces until an equivalent Go-owned runtime or validation path exists.",
			"Prefer staged retirement: generate parity evidence, merge the Go replacement, then freeze and remove the legacy path.",
			"Treat `main` as the only evolving branch; all migration branches rebase on current `main` before merge.",
		},
		FirstBatchExecution: []string{
			"Start `BIG-VNEXT-GO-102`, `BIG-VNEXT-GO-103`, and `BIG-VNEXT-GO-104` in parallel after this planning slice lands.",
			"Keep `BIG-VNEXT-GO-105` blocked until the root test and ops wrapper replacements have converged enough to avoid duplicating harness work.",
			"Use `BIG-VNEXT-GO-101` as the source of truth for remaining non-Go inventory and next-batch prioritization.",
		},
	}
}
