package uireview

func BuildBig4204ReviewPack() UIReviewPack {
	return UIReviewPack{
		IssueID:                   "BIG-4204",
		Title:                     "UI评审包输出",
		Version:                   "v4.0-design-sprint",
		RequiresReviewerChecklist: true,
		RequiresDecisionLog:       true,
		RequiresRoleMatrix:        true,
		RequiresSignoffLog:        true,
		RequiresBlockerLog:        true,
		RequiresBlockerTimeline:   true,
		Objectives: []ReviewObjective{
			{
				ObjectiveID:   "obj-overview-decision",
				Title:         "Validate the executive overview narrative and drill-down posture",
				Persona:       "VP Eng",
				Outcome:       "Leadership can confirm the overview page balances KPI density with investigation entry points.",
				SuccessSignal: "Reviewers agree the overview supports release, risk, and queue drill-down without extra walkthroughs.",
				Priority:      "P0",
				Dependencies:  []string{"BIG-4203", "OPE-132"},
			},
			{
				ObjectiveID:   "obj-queue-governance",
				Title:         "Confirm queue control actions and approval posture",
				Persona:       "Platform Admin",
				Outcome:       "Operators can assess batch approvals, audit visibility, and denial paths from one frame.",
				SuccessSignal: "The queue frame clearly shows allowed actions, denied roles, and audit expectations.",
				Priority:      "P0",
				Dependencies:  []string{"BIG-4203", "OPE-131", "OPE-132"},
			},
			{
				ObjectiveID:   "obj-run-detail-investigation",
				Title:         "Validate replay and audit investigation flow",
				Persona:       "Eng Lead",
				Outcome:       "Run detail reviewers can trace evidence, replay context, and escalation actions in one surface.",
				SuccessSignal: "The run-detail frame makes failure replay and escalation decisions reviewable without hidden dependencies.",
				Priority:      "P0",
				Dependencies:  []string{"BIG-4203", "OPE-72", "OPE-73"},
			},
			{
				ObjectiveID:   "obj-triage-handoff",
				Title:         "Confirm triage and cross-team handoff readiness",
				Persona:       "Cross-Team Operator",
				Outcome:       "Reviewers can evaluate assignment, handoff, and queue-state transitions as one operator journey.",
				SuccessSignal: "The triage frame exposes action states, owner switches, and handoff exceptions explicitly.",
				Priority:      "P0",
				Dependencies:  []string{"BIG-4203", "OPE-76", "OPE-79", "OPE-132"},
			},
		},
		Wireframes: []WireframeSurface{
			{
				SurfaceID:     "wf-overview",
				Name:          "Overview command deck",
				Device:        "desktop",
				EntryPoint:    "/overview",
				PrimaryBlocks: []string{"top bar", "kpi strip", "risk panel", "drill-down table"},
				ReviewNotes:   []string{"Confirm metric density and executive scan path.", "Check alert prominence versus weekly summary card."},
			},
			{
				SurfaceID:     "wf-queue",
				Name:          "Queue control center",
				Device:        "desktop",
				EntryPoint:    "/queue",
				PrimaryBlocks: []string{"approval queue", "selection toolbar", "filters", "audit rail"},
				ReviewNotes:   []string{"Validate batch-approve CTA hierarchy.", "Review denied-role behavior for non-operator personas."},
			},
			{
				SurfaceID:     "wf-run-detail",
				Name:          "Run detail and replay",
				Device:        "desktop",
				EntryPoint:    "/runs/detail",
				PrimaryBlocks: []string{"timeline", "artifact drawer", "replay controls", "audit notes"},
				ReviewNotes:   []string{"Check replay mode discoverability.", "Ensure escalation path is visible next to audit evidence."},
			},
			{
				SurfaceID:     "wf-triage",
				Name:          "Triage and handoff board",
				Device:        "desktop",
				EntryPoint:    "/triage",
				PrimaryBlocks: []string{"severity lanes", "bulk actions", "handoff panel", "ownership history"},
				ReviewNotes:   []string{"Validate cross-team operator workflow.", "Confirm exception path for denied escalation."},
			},
		},
		Interactions: []InteractionFlow{
			{
				FlowID:         "flow-overview-drilldown",
				Name:           "Overview to investigation drill-down",
				Trigger:        "VP Eng selects a KPI card or blocker cluster on the overview page",
				SystemResponse: "The console pivots into the matching queue or run-detail slice while preserving context filters.",
				States:         []string{"default", "focus", "handoff-ready"},
				Exceptions:     []string{"Warn when the requested slice is permission-denied.", "Show fallback summary when no matching runs exist."},
			},
			{
				FlowID:         "flow-queue-bulk-approval",
				Name:           "Queue batch approval review",
				Trigger:        "Platform Admin selects multiple tasks and opens the bulk approval toolbar",
				SystemResponse: "The queue shows approval scope, audit consequence, and denied-role messaging before submit.",
				States:         []string{"default", "selection", "confirming", "success"},
				Exceptions:     []string{"Disable submit when tasks cross unauthorized scopes.", "Route to audit timeline when approval policy changes mid-flow."},
			},
			{
				FlowID:         "flow-run-replay",
				Name:           "Run replay with evidence audit",
				Trigger:        "Eng Lead switches replay mode on a failed run",
				SystemResponse: "The page updates the timeline, artifacts, and escalation controls while keeping the audit trail visible.",
				States:         []string{"default", "replay", "compare", "escalated"},
				Exceptions:     []string{"Show replay-unavailable state for incomplete artifacts.", "Require escalation reason before handoff."},
			},
			{
				FlowID:         "flow-triage-handoff",
				Name:           "Triage ownership reassignment and handoff",
				Trigger:        "Cross-Team Operator bulk-assigns a finding set or opens the handoff panel",
				SystemResponse: "The triage board updates owner, workflow, and handoff evidence in one acknowledgement step.",
				States:         []string{"default", "selected", "handoff", "completed"},
				Exceptions:     []string{"Block handoff when reviewer coverage is incomplete.", "Record denied-role attempt in the audit summary."},
			},
		},
		OpenQuestions: []OpenQuestion{
			{QuestionID: "oq-role-density", Theme: "role-matrix", Question: "Should VP Eng see queue batch controls in read-only form or be routed to a summary-only state?", Owner: "product-experience", Impact: "Changes denial-path copy, button placement, and review criteria for queue and triage pages."},
			{QuestionID: "oq-alert-priority", Theme: "information-architecture", Question: "Should regression alerts outrank approval alerts in the top bar for the design sprint prototype?", Owner: "engineering-operations", Impact: "Affects alert hierarchy and the scan path used in the overview and triage reviews."},
			{QuestionID: "oq-handoff-evidence", Theme: "handoff", Question: "How much ownership history must stay visible before the run-detail and triage pages collapse older audit entries?", Owner: "orchestration-office", Impact: "Shapes the default density of the audit rail and the threshold for the review-ready packet."},
		},
		ReviewerChecklist: []ReviewerChecklistItem{
			{ItemID: "chk-overview-kpi-scan", SurfaceID: "wf-overview", Prompt: "Verify the KPI strip still supports one-screen executive scanning before drill-down.", Owner: "VP Eng", Status: "ready", EvidenceLinks: []string{"wf-overview", "flow-overview-drilldown"}, Notes: "Use the overview card hierarchy as the primary decision frame."},
			{ItemID: "chk-overview-alert-hierarchy", SurfaceID: "wf-overview", Prompt: "Confirm alert priority is readable when approvals and regressions compete for attention.", Owner: "engineering-operations", Status: "open", EvidenceLinks: []string{"wf-overview", "oq-alert-priority"}},
			{ItemID: "chk-queue-batch-approval", SurfaceID: "wf-queue", Prompt: "Check that batch approval clearly communicates scope, denial paths, and audit consequences.", Owner: "Platform Admin", Status: "ready", EvidenceLinks: []string{"wf-queue", "flow-queue-bulk-approval"}},
			{ItemID: "chk-queue-role-density", SurfaceID: "wf-queue", Prompt: "Validate whether VP Eng should get a summary-only queue variant instead of operator controls.", Owner: "product-experience", Status: "open", EvidenceLinks: []string{"wf-queue", "oq-role-density"}},
			{ItemID: "chk-run-replay-context", SurfaceID: "wf-run-detail", Prompt: "Ensure replay, compare, and escalation states remain distinguishable without narration.", Owner: "Eng Lead", Status: "ready", EvidenceLinks: []string{"wf-run-detail", "flow-run-replay"}},
			{ItemID: "chk-run-audit-density", SurfaceID: "wf-run-detail", Prompt: "Confirm the audit rail retains enough ownership history before collapsing older entries.", Owner: "orchestration-office", Status: "open", EvidenceLinks: []string{"wf-run-detail", "oq-handoff-evidence"}},
			{ItemID: "chk-triage-handoff-clarity", SurfaceID: "wf-triage", Prompt: "Check that cross-team handoff consequences are explicit before ownership changes commit.", Owner: "Cross-Team Operator", Status: "ready", EvidenceLinks: []string{"wf-triage", "flow-triage-handoff"}},
			{ItemID: "chk-triage-bulk-assign", SurfaceID: "wf-triage", Prompt: "Validate bulk assignment visibility without burying the audit context.", Owner: "Platform Admin", Status: "ready", EvidenceLinks: []string{"wf-triage", "flow-triage-handoff"}},
		},
		DecisionLog: []ReviewDecision{
			{DecisionID: "dec-overview-alert-stack", SurfaceID: "wf-overview", Owner: "product-experience", Summary: "Keep approval and regression alerts in one stacked priority rail.", Rationale: "Reviewers need one comparison lane before jumping into queue or triage surfaces.", Status: "accepted"},
			{DecisionID: "dec-queue-vp-summary", SurfaceID: "wf-queue", Owner: "VP Eng", Summary: "Route VP Eng to a summary-first queue state instead of operator controls.", Rationale: "The VP Eng persona needs queue visibility without accidental action affordances.", Status: "proposed", FollowUp: "Resolve after the next design critique with policy owners."},
			{DecisionID: "dec-run-detail-audit-rail", SurfaceID: "wf-run-detail", Owner: "Eng Lead", Summary: "Keep audit evidence visible beside replay controls in all replay states.", Rationale: "Replay decisions are inseparable from audit context and escalation evidence.", Status: "accepted"},
			{DecisionID: "dec-triage-handoff-density", SurfaceID: "wf-triage", Owner: "Cross-Team Operator", Summary: "Preserve ownership history in the triage rail until handoff is acknowledged.", Rationale: "Operators need a stable handoff trail before collapsing older events.", Status: "accepted"},
		},
		RoleMatrix: []ReviewRoleAssignment{
			{AssignmentID: "role-overview-vp-eng", SurfaceID: "wf-overview", Role: "VP Eng", Responsibilities: []string{"approve overview scan path", "validate KPI-to-drilldown narrative"}, ChecklistItemIDs: []string{"chk-overview-kpi-scan"}, DecisionIDs: []string{"dec-overview-alert-stack"}, Status: "ready"},
			{AssignmentID: "role-overview-eng-ops", SurfaceID: "wf-overview", Role: "engineering-operations", Responsibilities: []string{"review alert priority posture"}, ChecklistItemIDs: []string{"chk-overview-alert-hierarchy"}, DecisionIDs: []string{"dec-overview-alert-stack"}, Status: "open"},
			{AssignmentID: "role-queue-platform-admin", SurfaceID: "wf-queue", Role: "Platform Admin", Responsibilities: []string{"validate batch-approval copy", "confirm permission posture"}, ChecklistItemIDs: []string{"chk-queue-batch-approval"}, DecisionIDs: []string{"dec-queue-vp-summary"}, Status: "ready"},
			{AssignmentID: "role-queue-product-experience", SurfaceID: "wf-queue", Role: "product-experience", Responsibilities: []string{"tune summary-only VP variant"}, ChecklistItemIDs: []string{"chk-queue-role-density"}, DecisionIDs: []string{"dec-queue-vp-summary"}, Status: "open"},
			{AssignmentID: "role-run-detail-eng-lead", SurfaceID: "wf-run-detail", Role: "Eng Lead", Responsibilities: []string{"approve replay-state clarity", "confirm escalation adjacency"}, ChecklistItemIDs: []string{"chk-run-replay-context"}, DecisionIDs: []string{"dec-run-detail-audit-rail"}, Status: "ready"},
			{AssignmentID: "role-run-detail-orchestration-office", SurfaceID: "wf-run-detail", Role: "orchestration-office", Responsibilities: []string{"review audit density threshold"}, ChecklistItemIDs: []string{"chk-run-audit-density"}, DecisionIDs: []string{"dec-run-detail-audit-rail"}, Status: "open"},
			{AssignmentID: "role-triage-cross-team-operator", SurfaceID: "wf-triage", Role: "Cross-Team Operator", Responsibilities: []string{"approve handoff clarity", "validate ownership transition story"}, ChecklistItemIDs: []string{"chk-triage-handoff-clarity"}, DecisionIDs: []string{"dec-triage-handoff-density"}, Status: "ready"},
			{AssignmentID: "role-triage-platform-admin", SurfaceID: "wf-triage", Role: "Platform Admin", Responsibilities: []string{"confirm bulk-assign audit visibility"}, ChecklistItemIDs: []string{"chk-triage-bulk-assign"}, DecisionIDs: []string{"dec-triage-handoff-density"}, Status: "ready"},
		},
		SignoffLog: []ReviewSignoff{
			{SignoffID: "sig-overview-vp-eng", AssignmentID: "role-overview-vp-eng", SurfaceID: "wf-overview", Role: "VP Eng", Status: "approved", EvidenceLinks: []string{"chk-overview-kpi-scan", "dec-overview-alert-stack"}, Notes: "Overview narrative approved for design sprint review.", RequestedAt: "2026-03-10T09:00:00Z", DueAt: "2026-03-12T18:00:00Z", EscalationOwner: "design-program-manager", SLAStatus: "met"},
			{SignoffID: "sig-queue-platform-admin", AssignmentID: "role-queue-platform-admin", SurfaceID: "wf-queue", Role: "Platform Admin", Status: "approved", EvidenceLinks: []string{"chk-queue-batch-approval", "dec-queue-vp-summary"}, Notes: "Queue control actions meet operator review criteria.", RequestedAt: "2026-03-10T11:00:00Z", DueAt: "2026-03-13T18:00:00Z", EscalationOwner: "platform-ops-manager", SLAStatus: "met"},
			{SignoffID: "sig-run-detail-eng-lead", AssignmentID: "role-run-detail-eng-lead", SurfaceID: "wf-run-detail", Role: "Eng Lead", Status: "pending", EvidenceLinks: []string{"chk-run-replay-context", "dec-run-detail-audit-rail"}, Notes: "Waiting for final replay-state copy review.", RequestedAt: "2026-03-12T11:00:00Z", DueAt: "2026-03-15T18:00:00Z", EscalationOwner: "engineering-director", SLAStatus: "at-risk", ReminderOwner: "design-program-manager", ReminderChannel: "slack", LastReminderAt: "2026-03-14T09:45:00Z", NextReminderAt: "2026-03-15T10:00:00Z", ReminderCadence: "daily", ReminderStatus: "scheduled"},
			{SignoffID: "sig-triage-cross-team-operator", AssignmentID: "role-triage-cross-team-operator", SurfaceID: "wf-triage", Role: "Cross-Team Operator", Status: "approved", EvidenceLinks: []string{"chk-triage-handoff-clarity", "dec-triage-handoff-density"}, Notes: "Cross-team handoff flow approved for prototype review.", RequestedAt: "2026-03-11T14:00:00Z", DueAt: "2026-03-13T12:00:00Z", EscalationOwner: "cross-team-program-manager", SLAStatus: "met"},
		},
		BlockerLog: []ReviewBlocker{
			{BlockerID: "blk-run-detail-copy-final", SurfaceID: "wf-run-detail", SignoffID: "sig-run-detail-eng-lead", Owner: "product-experience", Summary: "Replay-state copy still needs final wording review before Eng Lead signoff can close.", Status: "open", Severity: "medium", EscalationOwner: "design-program-manager", NextAction: "Review replay-state copy with Eng Lead and update the run-detail frame in the next critique.", FreezeException: true, FreezeOwner: "release-director", FreezeUntil: "2026-03-18T18:00:00Z", FreezeReason: "Allow the design sprint review pack to ship while tracked copy cleanup lands in the next critique.", FreezeApprovedBy: "release-director", FreezeApprovedAt: "2026-03-14T08:30:00Z", FreezeRenewalOwner: "release-director", FreezeRenewalBy: "2026-03-17T12:00:00Z", FreezeRenewalStatus: "review-needed"},
		},
		BlockerTimeline: []ReviewBlockerEvent{
			{EventID: "evt-run-detail-copy-opened", BlockerID: "blk-run-detail-copy-final", Actor: "product-experience", Status: "opened", Summary: "Captured the final replay-state copy gap during design sprint prep.", Timestamp: "2026-03-13T10:00:00Z", NextAction: "Draft updated replay labels before the Eng Lead review."},
			{EventID: "evt-run-detail-copy-escalated", BlockerID: "blk-run-detail-copy-final", Actor: "design-program-manager", Status: "escalated", Summary: "Scheduled a joint wording review with Eng Lead and product-experience to close the signoff blocker.", Timestamp: "2026-03-14T09:30:00Z", NextAction: "Refresh the run-detail frame annotations after the wording review completes.", HandoffFrom: "product-experience", HandoffTo: "Eng Lead", Channel: "design-critique", ArtifactRef: "wf-run-detail#copy-v5", AckOwner: "Eng Lead", AckAt: "2026-03-14T10:15:00Z", AckStatus: "acknowledged"},
		},
	}
}
